UNStats/covid-19-response

gatsby-config.js
package.json
src/@undataforum/gatsby-theme-base/components/header.js
src/@undataforum/gatsby-theme-blog/i18n/translations/en.js
yarn.lock

Add second post collection

---

package.json
src/@undataforum/gatsby-theme-base/components/layout.js
src/gatsby-plugin-theme-ui/index.js
yarn.lock

Apply color scheme from UN web style guide

---

gatsby-config.js
src/@undataforum/gatsby-theme-base/components/header.js

Add title to header

---

now.json

Move Zeit deployment from undataforum to unstats

---

content/blurb.mdx
content/data-innovation/aute-ullamco-proident-ad-veniam-magna-ea-irure-sit.md
content/data-innovation/duis-do-eu-dolore-irure-aliquip-ea-ut-sunt-fugiat-dolore.md
content/open-data/aute-ullamco-proident-ad-veniam-magna-ea-irure-sit.md
content/open-data/duis-do-eu-dolore-irure-aliquip-ea-ut-sunt-fugiat-dolore.md
gatsby-config.js
package.json
src/@undataforum/gatsby-theme-base/components/header.js
src/@undataforum/gatsby-theme-blog/i18n/translations/en.js
src/components/post-list.js
src/pages/index.js
yarn.lock

Modify collections and change homepage layout

---

README.md
package.json

Revise homepage SEO description

---

gatsby-config.js
package.json
src/components/header.js
yarn.lock

Move site title into same line as topic in header

---

content/blurbs/about.mdx
content/blurbs/background.mdx
content/blurbs/data-collection.mdx
content/blurbs/data-innovation.mdx
content/blurbs/data-portals.mdx
content/blurbs/open-data.mdx
content/blurbs/work-arrangements.mdx
src/@undataforum/gatsby-theme-blog/components/posts-page.js
src/pages/index.js

Add blurb to post collections overview pages

---

src/@undataforum/gatsby-theme-base/pages/contact.md

Shadow contact page

---

content/blurbs/sharing.mdx

Add GPSDD mailing lists to 'share experiences'

---

content/blurbs/about.mdx

Revise about blurb

---

content/blurbs/sharing.mdx

Change contact email address

---

package.json
yarn.lock

Add support to launch production build locally

---

content/open-data/disseminate-and-incentivize-data-use.md
content/open-data/publish-existing-data-as-open-data.md
src/@undataforum/gatsby-theme-blog/i18n/translations/en.js

Post-launch edits

---

content/blurbs/about.mdx
package.json
src/pages/index.js

Fix URLs in sitemap.xml

---

src/pages/index.js

Add verification for Google Search Console

---

content/sharing/first-covid-19-stats-twitter-chat.md

Add first twitter chat

---

content/sharing/first-covid-19-stats-twitter-chat.md

Fix time zone of Twitter chat

---

package.json

Change config for local production build

---

content/work-remotely/statistics-elearning.md

Fix broken link

---

package.json
static/robots.txt
yarn.lock

Add robots.txt

---

gatsby-config.js
package.json
yarn.lock

Add Google analytics

---

content/blurbs/background.mdx
content/data-solutions/gender-disaggregated-data.md

Fix typo and other edits

---

src/components/footer.js

Left align footer on small screens

---

content/statistical-programmes/impact-on-labour-market-statistics.md

Add article - impact on labour statistics

---

content/sharing/paris21-webinar-how-are-nsos-doing.md

PARIS21 webinar announcement

---

content/work-remotely/conferencing-in-times-of-covid-19.md

Add "Conferencing in times of COVID-19"

---

content/sharing/paris21-webinar-how-are-nsos-doing.md

Fix time and timezone for PARIS21 webinar

---

content/statistical-programmes/use-of-admin-data-under-covid19.md
content/statistical-programmes/use-of-administrative-data-sources-under-covid-19.md
now.json

Edit administrative data post

---

content/blurbs/data-solutions.mdx
content/blurbs/open-data.mdx
content/blurbs/sharing.mdx
content/blurbs/statistical-programmes.mdx
content/blurbs/useful-links.mdx
content/blurbs/work-remotely.mdx

Change color of icons in overview pages to blue

---

content/useful-links/resources-from-national-statistical-offices.md

Add NSO COVID-19 resources

---

content/useful-links/resources-from-national-statistical-offices.md

Add Palestine links

---

content/useful-links/resources-from-national-statistical-offices.md

Add Ireland to NSO resources

---

content/useful-links/resources-from-national-statistical-offices.md

Link to StatsCan article from NSO resources page

---

content/useful-links/international-organisations-resources.md

Closes GH-174

---

content/statistical-programmes/telephone-surveys-what-to-consider.md

Add article on telephone surveys

---

content/sharing/data-in-the-fight-against-covid-19.md

Add United Nations World Data Forum webinar

---

content/statistical-programmes/impact-of-covid-19-on-the-implementation-of-statistical-surveys-in-iran.md

Add article

---

lint-staged.config.js
package.json
yarn.lock

Fix lint-staged.config.js

---

.github/workflows/code-qa.yml

Refactor GitHub action for Code QA

---

README.md
package.json
yarn.lock

Enable launching in CodeSandbox

---

package.json

Remove engines field from package.json

---

content/useful-links/international-organisations-resources.md

links escap

---

content/sharing/second-covid-19-stats-twitter-chat.md

update Twitter chat summary

---

.github/workflows/code-qa.yml
README.md
package.json

Switch back to Node v12

---

package.json

Remove test script

---

.github/CODEOWNERS

Change codeowners for /content

---

.github/CODEOWNERS

Change code ownership for /static

---

.github/workflows/code-qa.yml

Use `yarn install --frozen-lockfile` for CI

---

.eslintrc
package.json
yarn.lock

Use @maiertech/eslint-config for linting

---

.prettierrc
lint-staged.config.js
package.json
yarn.lock

Use @maiertech/prettier-config

---

content/useful-links/resources-from-national-statistical-offices.md

Add ABS links to resources from NSOs

---

content/statistical-programmes/interview-with-sir-ian-diamond-national-statistician-of-the-uk.md

closes #312 - Add UK Chief Statistician interview

Add ONS article

---

content/sharing/household-surveys-and-covid19-webinar.md

Household Surveys and COVID-19: Webinar

---

content/statistical-programmes/united-nations-statistical-offices.md

edit title of UNSD-RC post

---

.github/dependabot.yml

Switch Dependabot interval to weekly

---

package.json
yarn.lock

Remove cross-env

---

vercel.json

Simplify vercel.json

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore
.vscode/extensions.json
.vscode/settings.json

Add container config

---

package.json
src/@undataforum/gatsby-theme-base/components/header.js
src/gatsby-plugin-theme-ui/index.js
src/pages/index.js

Deep merge theme without deepmerge

---

content/useful-links/resources-from-national-statistical-offices.md

Add NSO resource - ONS telephone interview guidance

---

content/sharing/monitoring-the-state-of-statistical-operations.md

Add webinar: Monitoring the State of Statistical Operations

---

content/statistical-programmes/covid-19-widens-gulf-of-data-inequality.md

Replicate and rename covid19-nso-survey

---

content/statistical-programmes/covid19-nso-survey.mdx
content/statistical-programmes/dealing-with-disruption.md

update resources for blogpost

---

.huskyrc
.vscode/launch.json
.vscode/settings.json
package.json
yarn.lock

Extract husky config from package.json to .huskyrc

---

.vscode/extensions.json

Remove comment from extensions.json

---

content/open-data/hdx-making-covid19-data-accessible/index.mdx

Edit ocha blog post

---

content/useful-links/resources-from-national-statistical-offices/index.mdx

Update nso covid 19 portal link

---

.github/dependabot.yml

Switch Dependabot updates to monthly

---

content/statistical-programmes/ensuring-continuity-in-survey-operations/index.mdx

Add Ensuring continuity in survey operations

---

content/posts/keeping-labour-data-flowing-during-covid/index.mdx

Add blog post keeping-labour-data-flowing

---

content/posts/rapidly-innovating-to-produce-timely-data-on-violence-against-women/index.mdx

Timely data on violence against women post
